package eav.model;

public class AttributeName {

    //attr_type_id
    //users
    public static final int ATTR_TYPE_ID_USERS_ID = 1;
    public static final int ATTR_TYPE_ID_USERS_LOGIN = 2;
    public static final int ATTR_TYPE_ID_USERS_PASSWORD = 3;
    public static final int ATTR_TYPE_ID_USERS_LAST_LOGIN_DATE = 4;
    public static final int ATTR_TYPE_ID_USERS_ARCHVIVE = 5;
    public static final int ATTR_TYPE_ID_USERS_ROLE_ID = 6;

    //USER_STATUS
    public static final int ATTR_TYPE_ID_USER_STATUS_ID = 7;
    public static final int ATTR_TYPE_ID_USER_STATUS_DESCRIPTION = 8;

    //STUDENT_DETAIL
    public static final int ATTR_TYPE_ID_STUDENT_DETAIL_ID = 9;
    public static final int ATTR_TYPE_ID_STUDENT_DETAIL_POSITION_ID = 10;
    public static final int ATTR_TYPE_ID_STUDENT_DETAIL_USER_STATUS_ID = 11;
    public static final int ATTR_TYPE_ID_STUDENT_DETAIL_USER_ID = 12;

    //ROLE
    public static final int ATTR_TYPE_ID_ROLE_ID = 13;
    public static final int ATTR_TYPE_ID_ROLE_DESCRIPTION = 14;

    //RESUME_STATUS
    public static final int ATTR_TYPE_ID_RESUME_STATUS_ID = 15;
    public static final int ATTR_TYPE_ID_RESUME_STATUS_DESCRIPTION = 16;

    //RESUME_KNOWLEDGE
    public static final int ATTR_TYPE_ID_RESUME_KNOWLEDGE_ID = 17;
    public static final int ATTR_TYPE_ID_RESUME_KNOWLEDGE_KNOWLEDGE_LEVEL = 18;
    public static final int ATTR_TYPE_ID_RESUME_KNOWLEDGE_KNOWLEDGE_TYPE = 19;
    public static final int ATTR_TYPE_ID_RESUME_KNOWLEDGE_RESUME_ID = 20;

    //RESUME
    public static final int ATTR_TYPE_ID_RESUME_ID = 21;
    public static final int ATTR_TYPE_ID_RESUME_VERSION = 22;
    public static final int ATTR_TYPE_ID_RESUME_ERROR_DESCRIPTION = 23;
    public static final int ATTR_TYPE_ID_RESUME_MODIFIED_DATE = 24;
    public static final int ATTR_TYPE_ID_RESUME_APPROVED_DATE = 25;
    public static final int ATTR_TYPE_ID_RESUME_NAME = 26;
    public static final int ATTR_TYPE_ID_RESUME_SURNAME = 27;
    public static final int ATTR_TYPE_ID_RESUME_ENG_NAME = 28;
    public static final int ATTR_TYPE_ID_RESUME_ENG_SURNAME = 29;
    public static final int ATTR_TYPE_ID_RESUME_LAST_NAME = 30;
    public static final int ATTR_TYPE_ID_RESUME_EMAIL = 31;
    public static final int ATTR_TYPE_ID_RESUME_TELEPHONE_NUM = 32;
    public static final int ATTR_TYPE_ID_RESUME_SKYPE = 33;
    public static final int ATTR_TYPE_ID_RESUME_PHOTO_PATH = 34;
    public static final int ATTR_TYPE_ID_RESUME_RESUME_STATUS_ID = 35;
    public static final int ATTR_TYPE_ID_RESUME_USER_ID = 36;

    //QA_RESUME_DETAIL
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_ID = 37;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_INSTITUTE_OTHER_NAME = 38;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_COURSE = 39;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_FACULTY = 40;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_GRADUATION_YEAR = 41;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_IS_STUDENT = 42;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_OTHER_CONTACTS = 43;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_TRAINING_CENTER_INTEREST = 44;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_WORK_IN_NETCRACKER_INTEREST = 45;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_OTHER_INTEREST = 46;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_QA_DEVELOPMENT = 47;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_SOFTWARE_DEVELOPMENT = 48;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_OTHER_JOB_INTERESTS = 49;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_QA_EXPERT_WORK_TYPE = 50;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_QA_AUTOMATION_WORK_TYPE = 51;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_QA_DEVELOPMENT_WORK_TYPE = 52;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_SOFTWARE_DEVELOPMENT_WORK_TYPE = 53;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_LEADERSHIP_WORK_TYPE = 54;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_OTHER_WORK_TYPE_SPECIFIC = 55;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_SOFTWARE_DEV_LIFE_CYCLE = 56;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_QA_ROLE_IN_LIFE_CYCLE = 57;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_WHAT_IS_TEST_CASE = 58;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_WHAT_IS_DEFECT = 59;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_TESTING_TYPE = 60;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_NETWORK_TECHNOLOGY = 61;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_OOP = 62;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_DB_SQL = 63;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_CLIENT_SERVER_ARCHITECTURE = 64;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_OTHER_SKILL_LEVEL = 65;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_WORK_EXPERIENCE = 66;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_ENGLISH_READ_LEVEL = 67;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_ENGLISH_WRITE_LEVEL = 68;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_ENGLISH_SPEAK_LEVEL = 69;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_WHERE_YOU_KNOW_ABOUT_TC = 70;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_WHY_TAKE_YOU_IN_NETCRACKER = 71;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_MORE_INFORMATION_ADOUT_YOU = 72;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_INSTITUTE_ID = 73;
    public static final int ATTR_TYPE_ID_QA_RESUME_DETAIL_RESUME_ID = 74;

    //QA_INTERVIEW_RESULT_DETAIL
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_ID = 75;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_HR_COME_TO_INTERVIEW = 76;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_HR_WORK_WITH_USER = 77;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_HR_OTHER_INFORMATION = 78;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_HR_FINAL_ASSESSMENT = 79;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_1 = 80;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_2 = 81;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_3 = 82;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_4 = 83;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_5 = 84;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_6 = 85;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_1 = 86;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_2 = 87;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_3 = 88;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_4 = 89;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_FINAL_ASSESSMENT = 90;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_BASIC_INFORMATION = 91;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_OTHER_INFORMATION = 92;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_WORK_WITH_USER = 93;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_COME_TO_INTERVIEW = 94;
    public static final int ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_INTERVIEW_RESULT_ID = 95;

    //POSITION
    public static final int ATTR_TYPE_ID_POSITION_ID = 96;
    public static final int ATTR_TYPE_ID_POSITION_DESCRIPTION = 97;

    //MAIL_QUEUE
    public static final int ATTR_TYPE_ID_MAIL_QUEUE_ID = 98;
    public static final int ATTR_TYPE_ID_MAIL_QUEUE_ADDED_WHEN = 99;
    public static final int ATTR_TYPE_ID_MAIL_QUEUE_IS_SENT = 100;
    public static final int ATTR_TYPE_ID_MAIL_QUEUE_IS_INCORRECT_MAIL = 101;
    public static final int ATTR_TYPE_ID_MAIL_QUEUE_RECIVER_ADDRESS = 102;
    public static final int ATTR_TYPE_ID_MAIL_QUEUE_MESSAGE_SUBJECT = 103;
    public static final int ATTR_TYPE_ID_MAIL_QUEUE_MESSAGE_BODY = 104;

    //KNOWLEDGE_TYPE
    public static final int ATTR_TYPE_ID_KNOWLEDGE_TYPE_ID = 105;
    public static final int ATTR_TYPE_ID_KNOWLEDGE_TYPE_DESCRIPTION = 106;

    //INTERVIEW_SLOT
    public static final int ATTR_TYPE_ID_INTERVIEW_SLOT_ID = 107;
    public static final int ATTR_TYPE_ID_INTERVIEW_SLOT_TIME = 108;
    public static final int ATTR_TYPE_ID_INTERVIEW_SLOT_INTERVIEW_ID = 109;
    public static final int ATTR_TYPE_ID_INTERVIEW_SLOT_USER_ID = 110;

    //INTERVIEW_RESULT
    public static final int ATTR_TYPE_ID_INTERVIEW_RESULT_INTERVIEW_SLOT_ID = 111;
    public static final int ATTR_TYPE_ID_INTERVIEW_RESULT_IS_COME = 112;
    public static final int ATTR_TYPE_ID_INTERVIEW_RESULT_HR_USER_ID = 113;
    public static final int ATTR_TYPE_ID_INTERVIEW_RESULT_INTERVIEWER_USER_ID = 114;

    //INTERVIEW
    public static final int ATTR_TYPE_ID_INTERVIEW_ID = 115;
    public static final int ATTR_TYPE_ID_INTERVIEW_LOGIN = 116;
    public static final int ATTR_TYPE_ID_INTERVIEW_START_TIME = 117;
    public static final int ATTR_TYPE_ID_INTERVIEW_END_TIME = 118;
    public static final int ATTR_TYPE_ID_INTERVIEW_HR_TIME_FOR_INTERVIEW = 119;
    public static final int ATTR_TYPE_ID_INTERVIEW_INTERVIEW_TIME_FOR_INTERVIEW = 120;
    public static final int ATTR_TYPE_ID_INTERVIEW_TOTAL_PLACE_COUNT = 121;
    public static final int ATTR_TYPE_ID_INTERVIEW_AVAILABLE_PLACE_COUNT = 122;
    public static final int ATTR_TYPE_ID_INTERVIEW_INTERVIEW_COUNT = 123;
    public static final int ATTR_TYPE_ID_INTERVIEW_HR_COUNT = 124;
    public static final int ATTR_TYPE_ID_INTERVIEW_ENABLE = 125;
    public static final int ATTR_TYPE_ID_INTERVIEW_POSITION_ID = 126;

    //INSTITUTE
    public static final int ATTR_TYPE_ID_INSTITUTE_ID = 127;
    public static final int ATTR_TYPE_ID_INSTITUTE_DESCRIPTION = 128;

    //DEV_RESUME_DETAIL
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_ID = 129;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_INSTITUTE_OTHER_NAME = 130;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_COURCE = 131;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_FACULTY = 132;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_DEPARTMENT = 133;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_SPECIALITY = 134;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_GRADUATION_YEAR = 135;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_OTHER_CONTACTS = 136;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_TRAINING_CENTER_INTEREST = 137;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_WORK_IN_NETCRACKER_INTEREST = 138;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_OTHER_JOB_INTEREST = 139;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_BACK_END_INTEREST = 140;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_FRONT_END_INTEREST = 141;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_DB_INTEREST = 142;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_OTHER_WORK_TYPE_SPECIFIC = 143;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_OPP_LEVEL = 144;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_DB_LEVEL = 145;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_WEB_LEVEL = 146;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_USER_INTERFACE_LEVEL = 147;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_UML_LEVEL = 148;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_OTHER_SKILL_LEVEL = 149;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_WORK_EXPERIENCEL = 150;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_ENGLISH_READ_LEVEL = 151;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_ENGLISH_WRITE_LEVEL = 152;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_ENGLISH_SPEAK_LEVEL = 153;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_WHERE_YOU_KNOW_ABOUT_TC = 154;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_WHY_TAKE_YOU_IN_NETCRACKER = 155;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_MORE_INFORMATION_ABOUT_YOU = 156;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_INSTITUTE_ID = 157;
    public static final int ATTR_TYPE_ID_DEV_RESUME_DETAIL_RESUME_ID = 158;

    //DEV_INTERVIEW_RESULT_DETAIL
    public static final int ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_ID = 159;
    public static final int ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_JAVA_SKILL = 160;
    public static final int ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_SQL_SKILL = 161;
    public static final int ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_INTERVIEWER_OTHER_INFORMATION = 162;
    public static final int ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_INTERVIEWER_WORK_WITH_USER = 163;
    public static final int ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_HR_OTHER_INFORMATION = 164;
    public static final int ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_HR_WORK_WITH_USER = 165;
    public static final int ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_DEV_FINAL_ASSESSMENT = 166;
    public static final int ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_HR_FINAL_ASSESSMENT = 167;
    public static final int ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_INTERVIEW_RESULT_ID = 168;


    //attr_type_code
    //users
    public static final String ATTR_TYPE_CODE_USERS_ID = "ID";
    public static final String ATTR_TYPE_CODE_USERS_LOGIN = "LOGIN";
    public static final String ATTR_TYPE_CODE_USERS_PASSWORD = "PASSWORD";
    public static final String ATTR_TYPE_CODE_USERS_LAST_LOGIN_DATE = "LAST_LOGIN_DATE";
    public static final String ATTR_TYPE_CODE_USERS_ARCHVIVE = "ARCHVIVE";
    public static final String ATTR_TYPE_CODE_USERS_ROLE_ID = "ROLE_ID";

    //USER_STATUS
    public static final String ATTR_TYPE_CODE_USER_STATUS_ID = "ID";
    public static final String ATTR_TYPE_CODE_USER_STATUS_DESCRIPTION = "DESCRIPTION";

    //STUDENT_DETAIL
    public static final String ATTR_TYPE_CODE_STUDENT_DETAIL_ID = "ID";
    public static final String ATTR_TYPE_CODE_STUDENT_DETAIL_POSITION_ID = "POSITION_ID";
    public static final String ATTR_TYPE_CODE_STUDENT_DETAIL_USER_STATUS_ID = "USER_STATUS_ID";
    public static final String ATTR_TYPE_CODE_STUDENT_DETAIL_USER_ID = "USER_ID";

    //ROLE
    public static final String ATTR_TYPE_CODE_ROLE_ID = "ID";
    public static final String ATTR_TYPE_CODE_ROLE_DESCRIPTION = "DESCRIPTION";

    //RESUME_STATUS
    public static final String ATTR_TYPE_CODE_RESUME_STATUS_ID = "ID";
    public static final String ATTR_TYPE_CODE_RESUME_STATUS_DESCRIPTION = "DESCRIPTION";

    //RESUME_KNOWLEDGE
    public static final String ATTR_TYPE_CODE_RESUME_KNOWLEDGE_ID = "ID";
    public static final String ATTR_TYPE_CODE_RESUME_KNOWLEDGE_KNOWLEDGE_LEVEL = "KNOWLEDGE_LEVEL";
    public static final String ATTR_TYPE_CODE_RESUME_KNOWLEDGE_KNOWLEDGE_TYPE = "KNOWLEDGE_TYPE";
    public static final String ATTR_TYPE_CODE_RESUME_KNOWLEDGE_RESUME_ID = "RESUME_ID";

    //RESUME
    public static final String ATTR_TYPE_CODE_RESUME_ID = "ID";
    public static final String ATTR_TYPE_CODE_RESUME_VERSION = "VERSION";
    public static final String ATTR_TYPE_CODE_RESUME_ERROR_DESCRIPTION = "ERROR_DESCRIPTION";
    public static final String ATTR_TYPE_CODE_RESUME_MODIFIED_DATE = "MODIFIED_DATE";
    public static final String ATTR_TYPE_CODE_RESUME_APPROVED_DATE = "APPROVED_DATE";
    public static final String ATTR_TYPE_CODE_RESUME_NAME = "NAME";
    public static final String ATTR_TYPE_CODE_RESUME_SURNAME = "SURNAME";
    public static final String ATTR_TYPE_CODE_RESUME_ENG_NAME = "ENG_NAME";
    public static final String ATTR_TYPE_CODE_RESUME_ENG_SURNAME = "ENG_SURNAME";
    public static final String ATTR_TYPE_CODE_RESUME_LAST_NAME = "LAST_NAME";
    public static final String ATTR_TYPE_CODE_RESUME_EMAIL = "EMAIL";
    public static final String ATTR_TYPE_CODE_RESUME_TELEPHONE_NUM = "TELEPHONE_NUM";
    public static final String ATTR_TYPE_CODE_RESUME_SKYPE = "SKYPE";
    public static final String ATTR_TYPE_CODE_RESUME_PHOTO_PATH = "PHOTO_PATH";
    public static final String ATTR_TYPE_CODE_RESUME_RESUME_STATUS_ID = "RESUME_STATUS_ID";
    public static final String ATTR_TYPE_CODE_RESUME_USER_ID = "USER_ID";

    //QA_RESUME_DETAIL
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_ID = "ID";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_INSTITUTE_OTHER_NAME = "INSTITUTE_OTHER_NAME";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_COURSE = "COURSE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_FACULTY = "FACULTY";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_GRADUATION_YEAR = "GRADUATION_YEAR";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_IS_STUDENT = "IS_STUDENT";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_IS_OTHER_CONTACTS = "OTHER_CONTACTS";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_TRAINING_CENTER_INTEREST = "TRAINING_CENTER_INTEREST";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_WORK_IN_NETCRACKER_INTEREST = "WORK_IN_NETCRACKER_INTEREST";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_OTHER_INTEREST = "OTHER_INTEREST";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_QA_DEVELOPMENT = "QA_DEVELOPMENT";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_SOFTWARE_DEVELOPMENT = "SOFTWARE_DEVELOPMENT";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_OTHER_JOB_INTERESTS = "OTHER_JOB_INTERESTS";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_QA_EXPERT_WORK_TYPE = "QA_EXPERT_WORK_TYPE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_QA_AUTOMATION_WORK_TYPE = "QA_AUTOMATION_WORK_TYPE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_QA_DEVELOPMENT_WORK_TYPE = "QA_DEVELOPMENT_WORK_TYPE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_SOFTWARE_DEVELOPMENT_WORK_TYPE = "SOFTWARE_DEVELOPMENT_WORK_TYPE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_LEADERSHIP_WORK_TYPE = "LEADERSHIP_WORK_TYPE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_OTHER_WORK_TYPE_SPECIFIC = "OTHER_WORK_TYPE_SPECIFIC";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_SOFTWARE_DEV_LIFE_CYCLE = "SOFTWARE_DEV_LIFE_CYCLE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_QA_ROLE_IN_LIFE_CYCLE = "QA_ROLE_IN_LIFE_CYCLE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_WHAT_IS_TEST_CASE = "WHAT_IS_TEST_CASE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_WHAT_IS_DEFECT = "WHAT_IS_DEFECT";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_TESTING_TYPE = "TESTING_TYPE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_NETWORK_TECHNOLOGY = "NETWORK_TECHNOLOGY";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_OOP = "OOP";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_DB_SQL = "DB_SQL";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_CLIENT_SERVER_ARCHITECTURE = "CLIENT_SERVER_ARCHITECTURE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_OTHER_SKILL_LEVEL = "OTHER_SKILL_LEVEL";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_WORK_EXPERIENCE = "WORK_EXPERIENCE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_ENGLISH_READ_LEVEL = "ENGLISH_READ_LEVEL";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_ENGLISH_WRITE_LEVEL = "ENGLISH_WRITE_LEVEL";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_ENGLISH_SPEAK_LEVEL = "ENGLISH_SPEAK_LEVEL";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_WHERE_YOU_KNOW_ABOUT_TC = "WHERE_YOU_KNOW_ABOUT_TC";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_WHY_TAKE_YOU_IN_NETCRACKER = "WHY_TAKE_YOU_IN_NETCRACKER";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_MORE_INFORMATION_ADOUT_YOU = "MORE_INFORMATION_ADOUT_YOU";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_INSTITUTE_ID = "INSTITUTE_ID";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_RESUME_ID = "RESUME_ID";

    //QA_INTERVIEW_RESULT_DETAIL
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_ID = "ID";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_HR_COME_TO_INTERVIEW = "HR_COME_TO_INTERVIEW";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_HR_WORK_WITH_USER = "HR_WORK_WITH_USER";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_HR_OTHER_INFORMATION = "HR_OTHER_INFORMATION";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_HR_FINAL_ASSESSMENT = "HR_FINAL_ASSESSMENT";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_1 = "QA_KNOWLEDGE_1";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_2 = "QA_KNOWLEDGE_2";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_3 = "QA_KNOWLEDGE_3";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_4 = "QA_KNOWLEDGE_4";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_5 = "QA_KNOWLEDGE_5";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_6 = "QA_KNOWLEDGE_6";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_1 = "IT_KNOWLEDGE_1";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_2 = "IT_KNOWLEDGE_2";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_3 = "IT_KNOWLEDGE_3";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_4 = "IT_KNOWLEDGE_4";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_FINAL_ASSESSMENT = "INTERVIEWER_FINAL_ASSESSMENT";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_BASIC_INFORMATION = "INTERVIEWER_BASIC_INFORMATION";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_OTHER_INFORMATION = "INTERVIEWER_OTHER_INFORMATION";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_WORK_WITH_USER = "INTERVIEWER_WORK_WITH_USER";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_COME_TO_INTERVIEW = "INTERVIEWER_COME_TO_INTERVIEW";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_INTERVIEW_RESULT_ID = "INTERVIEW_RESULT_ID";

    //POSITION
    public static final String ATTR_TYPE_CODE_POSITION_ID = "ID";
    public static final String ATTR_TYPE_CODE_POSITION_DESCRIPTION = "DESCRIPTION";

    //MAIL_QUEUE
    public static final String ATTR_TYPE_CODE_MAIL_QUEUE_ID = "ID";
    public static final String ATTR_TYPE_CODE_MAIL_QUEUE_ADDED_WHEN = "ADDED_WHEN";
    public static final String ATTR_TYPE_CODE_MAIL_QUEUE_IS_SENT = "IS_SENT";
    public static final String ATTR_TYPE_CODE_MAIL_IS_INCORRECT_MAIL = "IS_INCORRECT_MAIL";
    public static final String ATTR_TYPE_CODE_MAIL_RECIVER_ADDRESS = "RECIVER_ADDRESS";
    public static final String ATTR_TYPE_CODE_MAIL_MESSAGE_SUBJECT = "MESSAGE_SUBJECT";
    public static final String ATTR_TYPE_CODE_MAIL_MESSAGE_BODY = "MESSAGE_BODY";

    //KNOWLEDGE_TYPE
    public static final String ATTR_TYPE_CODE_KNOWLEDGE_TYPE_ID = "ID";
    public static final String ATTR_TYPE_CODE_KNOWLEDGE_TYPE_DESCRIPTION = "DESCRIPTION";

    //INTERVIEW_SLOT
    public static final String ATTR_TYPE_CODE_INTERVIEW_SLOT_ID = "ID";
    public static final String ATTR_TYPE_CODE_INTERVIEW_SLOT_TIME = "TIME";
    public static final String ATTR_TYPE_CODE_INTERVIEW_SLOT_INTERVIEW_ID = "INTERVIEW_ID";
    public static final String ATTR_TYPE_CODE_INTERVIEW_SLOT_USER_ID = "USER_ID";

    //INTERVIEW_RESULT
    public static final String ATTR_TYPE_CODE_INTERVIEW_RESULT_INTERVIEW_SLOT_ID = "INTERVIEW_SLOT_ID";
    public static final String ATTR_TYPE_CODE_INTERVIEW_RESULT_IS_COME = "IS_COME";
    public static final String ATTR_TYPE_CODE_INTERVIEW_RESULT_HR_USER_ID = "HR_USER_ID";
    public static final String ATTR_TYPE_CODE_INTERVIEW_RESULT_INTERVIEWER_USER_ID = "INTERVIEWER_USER_ID";

    //INTERVIEW
    public static final String ATTR_TYPE_CODE_INTERVIEW_ID = "ID";
    public static final String ATTR_TYPE_CODE_INTERVIEW_LOGIN = "LOGIN";
    public static final String ATTR_TYPE_CODE_INTERVIEW_START_TIME = "START_TIME";
    public static final String ATTR_TYPE_CODE_INTERVIEW_END_TIME = "END_TIME";
    public static final String ATTR_TYPE_CODE_INTERVIEW_HR_TIME_FOR_INTERVIEW = "HR_TIME_FOR_INTERVIEW";
    public static final String ATTR_TYPE_CODE_INTERVIEW_INTERVIEW_TIME_FOR_INTERVIEW = "INTERVIEW_TIME_FOR_INTERVIEW";
    public static final String ATTR_TYPE_CODE_INTERVIEW_INTERVIEW_TOTAL_PLACE_COUNT = "TOTAL_PLACE_COUNT";
    public static final String ATTR_TYPE_CODE_INTERVIEW_INTERVIEW_AVAILABLE_PLACE_COUNT = "AVAILABLE_PLACE_COUNT";
    public static final String ATTR_TYPE_CODE_INTERVIEW_INTERVIEW_INTERVIEW_COUNT = "INTERVIEW_COUNT";
    public static final String ATTR_TYPE_CODE_INTERVIEW_INTERVIEW_HR_COUNT = "HR_COUNT";
    public static final String ATTR_TYPE_CODE_INTERVIEW_INTERVIEW_ENABLE = "ENABLE";
    public static final String ATTR_TYPE_CODE_INTERVIEW_INTERVIEW_POSITION_ID = "POSITION_ID";

    //INSTITUTE
    public static final String ATTR_TYPE_CODE_INSTITUTE_ID = "ID";
    public static final String ATTR_TYPE_CODE_INSTITUTE_DESCRIPTION = "DESCRIPTION";

    //DEV_RESUME_DETAIL
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_ID = "ID";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_INSTITUTE_OTHER_NAME = "INSTITUTE_OTHER_NAME";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_COURCE = "COURCE";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_FACULTY = "FACULTY";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_DEPARTMENT = "DEPARTMENT";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_SPECIALITY = "SPECIALITY";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_GRADUATION_YEAR = "GRADUATION_YEAR";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_OTHER_CONTACTS = "OTHER_CONTACTS";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_TRAINING_CENTER_INTEREST = "TRAINING_CENTER_INTEREST";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_WORK_IN_NETCRACKER_INTEREST = "WORK_IN_NETCRACKER_INTEREST";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_OTHER_JOB_INTEREST = "OTHER_JOB_INTEREST";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_BACK_END_INTEREST = "BACK_END_INTEREST";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_FRONT_END_INTEREST = "FRONT_END_INTEREST";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_DB_INTEREST = "DB_INTEREST";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_OTHER_WORK_TYPE_SPECIFIC = "OTHER_WORK_TYPE_SPECIFIC";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_OPP_LEVEL = "OPP_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_DB_LEVEL = "DB_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_WEB_LEVEL = "WEB_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_USER_INTERFACE_LEVEL = "USER_INTERFACE_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_UML_LEVEL = "UML_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_OTHER_SKILL_LEVEL = "OTHER_SKILL_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_WORK_EXPERIENCE = "WORK_EXPERIENCE";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_ENGLISH_READ_LEVEL = "ENGLISH_READ_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_ENGLISH_WRITE_LEVEL = "ENGLISH_WRITE_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_ENGLISH_SPEAK_LEVEL = "ENGLISH_SPEAK_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_WHERE_YOU_KNOW_ABOUT_TC = "WHERE_YOU_KNOW_ABOUT_TC";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_WHY_TAKE_YOU_IN_NETCRACKER = "WHY_TAKE_YOU_IN_NETCRACKER";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_MORE_INFORMATION_ABOUT_YOU = "MORE_INFORMATION_ABOUT_YOU";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_INSTITUTE_ID = "INSTITUTE_ID";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_RESUME_ID = "RESUME_ID";

    //DEV_INTERVIEW_RESULT_DETAIL
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_ID = "ID";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_JAVA_SKILL = "JAVA_SKILL";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_SQL_SKILL = "SQL_SKILL";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_INTERVIEWER_OTHER_INFORMATION = "INTERVIEWER_OTHER_INFORMATION";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_INTERVIEWER_WORK_WITH_USER = "INTERVIEWER_WORK_WITH_USER";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_HR_OTHER_INFORMATION = "HR_OTHER_INFORMATION";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_HR_WORK_WITH_USER = "HR_WORK_WITH_USER";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_DEV_FINAL_ASSESSMENT = "DEV_FINAL_ASSESSMENT";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_HR_FINAL_ASSESSMENT = "HR_FINAL_ASSESSMENT";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_INTERVIEW_RESULT_ID = "INTERVIEW_RESULT_ID";

}
